---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{.name}}-{{.Iteration}}-{{.Replica}}
spec:
  selector:
    matchLabels:
      app: {{.name}}-{{.Iteration}}-{{.Replica}}
  template:
    metadata:
      labels:
        app: {{.name}}-{{.Iteration}}-{{.Replica}}
    spec:
      nodeSelector:
        {{.nodeSelectorKey}}: {{.nodeSelectorValue}}
      containers:
      - args:
        - sleep
        - infinity
        image: quay.io/multi-arch/cloud-bulldozer:hello-openshift
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        name: {{.name}}
