apiVersion: bench.example.com/v1alpha1
kind: Bench
metadata:
  name: example-bench
spec:
  uperf: 
    # Server size must always be 1 or more
    pair: 2
    proto: tcp
    test_type: stream
    nthr: 2
    size: 16384
    runtime: 60
